openapi: 3.0.0
info:
  title: Cog Smart API spec
  description: api for SAMD
  version: 1.0.0
servers:
  - url: 'http://localhost:3001/'
    description: Server URL
security:
  - Bearer: []
  - api_key: [device, apptype, token]
paths:
  #### Auth
  /v1/auth/family/sign-in:
    post:
      tags:
        - Auth
      summary: Family login
      description: Family login
      requestBody:
        description: Family login
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login success
          content:
            application/json:
              schema:
                properties:
                  access_token:
                    type: string
                    example: >-
                      eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUwMDUwMDA1MDAwIiwibmFtZSI6IiDjgY3jgY0gIiwibmFtZUthdGFrYW5hIjoiIOOCq-OCv-OCq-ODiiAiLCJnZW5kZXIiOm51bGwsInN1YiI6NDkxLCJ0eXBlIjoyLCJwYXRpZW50SWQiOjQ5MCwicGF0aWVudE5hbWUiOiJFeHBpcmUgYWJub3JtYWwgRXhwaXJlIGFibm9ybWFsIiwiYXBwVHlwZSI6MCwicHJlc2NyaXB0aW9uSWQiOjU2NywiaWF0IjoxNjc5NzM1MzQzLCJleHAiOjE2Nzk4MjE3NDN9.JOL2cojbME2UZkdYJTWB9tkqA5vVdLPg7V2wvtQNMhU
                  refreshToken:
                    type: string
                    example: >-
                      eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUwMDUwMDA1MDAwIiwibmFtZSI6IiDjgY3jgY0gIiwibmFtZUthdGFrYW5hIjoiIOOCq-OCv-OCq-ODiiAiLCJnZW5kZXIiOm51bGwsInN1YiI6NDkxLCJ0eXBlIjoyLCJwYXRpZW50SWQiOjQ5MCwicGF0aWVudE5hbWUiOiJFeHBpcmUgYWJub3JtYWwgRXhwaXJlIGFibm9ybWFsIiwiYXBwVHlwZSI6MCwicHJlc2NyaXB0aW9uSWQiOjU2NywiaWF0IjoxNjc5NzM1MzQzfQ.j5HCDZkyL6wKB2MXnvsIvCR6iQAozMo5Egb_NMr2SWQ
                  id:
                    type: string
                    example: 50050005000
                  name:
                    type: string
                    example: きき
                  nameKatakana:
                    type: string
                    example: カタカナ
                  sub:
                    type: number
                    example: 491
                  type:
                    type: number
                    example: 2
                  patientId:
                    type: number
                    example: 490
                  patientName:
                    type: string
                    example: Sakura
                  level:
                    type: number
                    example: 3
                  isLoginBefore:
                    type: number
                    example: 1
                  prescriptions:
                    type: object
                    example: [
                            {
                                "id": 567,
                                "doctorId": 8,
                                "startTime": "2023-03-23T08:00:00.000Z",
                                "endTime": "2023-04-01T07:59:59.000Z",
                                "hasReminder": 1,
                                "hasExecutionLog": 1,
                                "hasIdSharing": 1
                            }
                        ]
                  maxExerciseIntensityRatio:
                    type: number
                    example: 0.8
                  minExerciseIntensityRatio:
                    type: number
                    example: 0.4
                  ageOfPatient:
                    type: number
                    example: 50
                  appType:
                    type: number
                    example: 1
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
  /v1/auth/patient/sign-in:
    post:
      tags:
        - Auth
      summary: Patient sign in
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Complete response
          content:
            application/json:
              schema:
                properties:
                  access_token:
                    type: string
                    example: >-
                      eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE5NjYiLCJuYW1lIjoiS3VyaWhhcmEgTWVndW1pICIsIm5hbWVLYXRha2FuYSI6IuOCtyDjg6EgIiwiZ2VuZGVyIjoiTWFsZSIsInN1YiI6NDkyLCJ0eXBlIjoxLCJhcHBUeXBlIjoxLCJwcmVzY3JpcHRpb25JZCI6NTY5LCJpYXQiOjE2Nzk3MzE3OTUsImV4cCI6MTY3OTgxODE5NX0.EdD3bU7_7Q_33aCiuRPnpv0Zi3W3Tfwr07VhlKIEo7E
                  refreshToken:
                    type: string
                    example: >-
                      eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE5NjYiLCJuYW1lIjoiS3VyaWhhcmEgTWVndW1pICIsIm5hbWVLYXRha2FuYSI6IuOCtyDjg6EgIiwiZ2VuZGVyIjoiTWFsZSIsInN1YiI6NDkyLCJ0eXBlIjoxLCJhcHBUeXBlIjoxLCJwcmVzY3JpcHRpb25JZCI6NTY5LCJpYXQiOjE2Nzk3MzE3OTV9.oKIZuNWCEWrnE5lMjz2_9uLixTyQ0FEiB1BdCyThHfQ
                  id:
                    type: string
                    example: 1996
                  name:
                    type: string
                    example: Kurihara Megumi
                  nameKatakana:
                    type: string
                    example: シ メ 
                  age:
                    type: number
                    example: 50
                  gender:
                    type: string
                    example: 男性
                  type:
                    type: number
                    example: 1
                  sub:
                    type: number
                    example: 492
                  isLoginBefore:
                    type: number
                    example: 1
                  level:
                    type: number
                    example: 3
                  prescriptions:
                    type: object
                    example: [
                            {
                                "id": 568,
                                "doctorId": 8,
                                "startTime": "2023-03-24T08:00:00.000Z",
                                "endTime": "2023-03-25T07:59:59.000Z",
                                "hasReminder": 1,
                                "hasExecutionLog": 0,
                                "hasIdSharing": 0
                            },
                            {
                                "id": 569,
                                "doctorId": 8,
                                "startTime": "2023-03-25T08:00:00.000Z",
                                "endTime": "2023-03-26T07:59:59.000Z",
                                "hasReminder": 1,
                                "hasExecutionLog": 1,
                                "hasIdSharing": 0
                            },
                            {
                                "id": 570,
                                "doctorId": 8,
                                "startTime": "2023-03-26T08:00:00.000Z",
                                "endTime": "2023-03-27T07:59:59.000Z",
                                "hasReminder": 1,
                                "hasExecutionLog": 0,
                                "hasIdSharing": 1
                            }
                        ]
                  appType:
                    type: number
                    example: 1
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
  /v1/auth/access-token:
    post:
      tags:
        - Auth
      summary: Get new access token
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                refreshToken:
                  type: string
      responses:
        '200':
          description: Return new access token
          content:
            application/json:
              schema:
                properties:
                  access_token:
                    type: string
                    example: >-
                      eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk5OTkxMjQiLCJuYW1lIjoi5rCPIOWQjSAiLCJuYW1lS2F0YWthbmEiOiLjgrcg44Oh44KkICIsImdlbmRlciI6Ik1hbGUiLCJzdWIiOjUxNSwidHlwZSI6MSwiYXBwVHlwZSI6MSwicHJlc2NyaXB0aW9uSWQiOjU0OSwiaWF0IjoxNjc5NjI4MTM0LCJleHAiOjE2Nzk3MTQ1MzR9.SiVS-o5-tw3sGSrKjdpDCwBbiP5UlKcdBsTLXFco8Q4
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
  /v1/auth/family/sign-up/verify/{patientId}:
    post:
      tags:
        - Auth
      summary: Verify patient id
      parameters:
        - name: patientId
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Verify success
          content:
            application/json:
              schema:
                type: boolean
                example: true
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
  /v1/auth/family/sign-up/verify-patient:
    post:
      tags:
        - Auth
      summary: Verify patient info
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                password:
                  type: string
                hospitalId:
                  type: number
      responses:
        '200':
          description: Verify success
          content:
            application/json:
              schema:
                type: boolean
                example: true
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
  /v1/auth/forgot-password/verify:
    post:
      tags:
        - Auth
      summary: Enter correct family phone number and patient birthday to verify
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                familyPhone:
                  type: string
                patientBirthday:
                  type: string
      responses:
        '200':
          description: Verify success
          content:
            application/json:
              schema:
                type: boolean
                example: true
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
  /v1/auth/forgot-password:
    post:
      tags:
        - Auth
      summary: Enter new password
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  example: '11122222222'
                newPassword:
                  type: string
                matchPassword:
                  type: string
      responses:
        '200':
          description: Renew password success
          content:
            application/json:
              schema:
                properties:
                  code:
                    type: number
                    example: 200
                  data:
                    type: string
                    example: ""
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
  /v1/auth/family/sign-up:
    post:
      tags:
        - Auth
      summary: Register new family account
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                phone:
                  type: string
                  example: '111-2222-2222'
                password:
                  type: string
                name:
                  type: string
                katakanaName:
                  type: string
                relation:
                  type: string
                patientId:
                  type: number
      responses:
        '200':
          description: Registration success
          content:
            application/json:
              schema:
                properties:
                  access_token:
                    type: string
                    example: >-
                      eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUwMDUwMDA1MDAwIiwibmFtZSI6IiDjgY3jgY0gIiwibmFtZUthdGFrYW5hIjoiIOOCq-OCv-OCq-ODiiAiLCJnZW5kZXIiOm51bGwsInN1YiI6NDkxLCJ0eXBlIjoyLCJwYXRpZW50SWQiOjQ5MCwicGF0aWVudE5hbWUiOiJFeHBpcmUgYWJub3JtYWwgRXhwaXJlIGFibm9ybWFsIiwiYXBwVHlwZSI6MCwicHJlc2NyaXB0aW9uSWQiOjU2NywiaWF0IjoxNjc5NzM1MzQzLCJleHAiOjE2Nzk4MjE3NDN9.JOL2cojbME2UZkdYJTWB9tkqA5vVdLPg7V2wvtQNMhU
                  refreshToken:
                    type: string
                    example: >-
                      eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUwMDUwMDA1MDAwIiwibmFtZSI6IiDjgY3jgY0gIiwibmFtZUthdGFrYW5hIjoiIOOCq-OCv-OCq-ODiiAiLCJnZW5kZXIiOm51bGwsInN1YiI6NDkxLCJ0eXBlIjoyLCJwYXRpZW50SWQiOjQ5MCwicGF0aWVudE5hbWUiOiJFeHBpcmUgYWJub3JtYWwgRXhwaXJlIGFibm9ybWFsIiwiYXBwVHlwZSI6MCwicHJlc2NyaXB0aW9uSWQiOjU2NywiaWF0IjoxNjc5NzM1MzQzfQ.j5HCDZkyL6wKB2MXnvsIvCR6iQAozMo5Egb_NMr2SWQ
                  id:
                    type: string
                    example: 50050005000
                  name:
                    type: string
                    example: きき
                  nameKatakana:
                    type: string
                    example: カタカナ
                  sub:
                    type: number
                    example: 491
                  type:
                    type: number
                    example: 2
                  patientId:
                    type: number
                    example: 490
                  patientName:
                    type: string
                    example: Sakura
                  level:
                    type: number
                    example: 3
                  isLoginBefore:
                    type: number
                    example: 1
                  prescriptions:
                    type: object
                    example: [
                            {
                                "id": 567,
                                "doctorId": 8,
                                "startTime": "2023-03-23T08:00:00.000Z",
                                "endTime": "2023-04-01T07:59:59.000Z",
                                "hasReminder": 1,
                                "hasExecutionLog": 1,
                                "hasIdSharing": 1
                            }
                        ]
                  maxExerciseIntensityRatio:
                    type: number
                    example: 0.8
                  minExerciseIntensityRatio:
                    type: number
                    example: 0.4
                  ageOfPatient:
                    type: number
                    example: 50
                  appType:
                    type: number
                    example: 1
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
  /v1/auth/family/verify-phone:
    post:
      tags:
        - Auth
      summary: Verify phone number
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                phone:
                  type: string
                  example: '111-2222-2222'
      responses:
        '200':
          description: Verify success
          content:
            application/json:
              schema:
                type: boolean
                example: true
        '400':
          description: Phone number is registered
          content:
            application/json:
              schema:
                properties:
                  errors:
                    type: string
                    example: BadRequestException
                  message:
                    type: string
                    example: 既にご登録のある連絡先（電話番号）です。
        '500':
          $ref: '#/components/responses/500'
  /v1/auth/family/logout/{token}:
    delete:
      tags:
        - Auth
      summary: Logout the account
      parameters:
        - name: token
          in: path
          schema:
            type: string
          required: true
      responses:
        '204':
          description: No Content
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
  /v1/auth/hospitals:
    post:
      tags:
        - Auth
      summary: Verify the hospital id
      parameters:
        - name: id
          in: query
          description: id
          schema:
            type: number
          required: true
      responses:
        '204':
          description: Verify success
          content:
            application/json:
              schema:
                type: boolean
                example: true
        '400':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'          
  #### Users
  /v1/users/patient:
    get:
      tags:
        - Users
      summary: Get patient info
      parameters:
        - name: userId
          in: query
          schema:
            type: number
          required: true
      responses:
        '200':
          description: Renew password success
          content:
            application/json:
              schema:
                properties:
                  codeRegister:
                    type: number
                    example: 200
                  name:
                    type: string
                    example: ""
                  katakanaName:
                    type: number
                    example: 200
                  gender:
                    type: string
                    example: ""
                  age:
                    type: number
                    example: 200
                  doctorInCharge:
                    type: string
                    example: ""
                  hospitalId:
                    type: number
                    example: 200
                  level:
                    type: string
                    example: ""
                  prescriptions:
                    type: number
                    example: 200
                  prescriptionId:
                    type: string
                    example: ""
                  minExerciseIntensityRatio:
                    type: number
                    example: 200
                  maxExerciseIntensityRatio:
                    type: string
                    example: ""
                  restingHeartRate:
                    type: number
                    example: 200
                  targetExerciseTime:
                    type: string
                    example: ""
                  enableSoundForReminder:
                    type: boolean
                    example: true
                  enableSoundForActivity:
                    type: boolean
                    example: true
                  enableSoundForCompleteActivity:
                    type: boolean
                    example: true
                  enableSoundForAchieveActivity:
                    type: boolean
                    example: true
                  enableSoundForAbnormal:
                    type: boolean
                    example: true
        '400':
          description: Phone number is registered
          content:
            application/json:
              schema:
                properties:
                  errors:
                    type: string
                    example: BadRequestException
                  message:
                    type: string
                    example: 既にご登録のある連絡先（電話番号）です。
        '500':
          $ref: '#/components/responses/500'
  #### Team Challenge
  /team-challenges:
    get:
      tags:
        - Team Challenge
      summary: List Team Challenge
      description: List Team Challenge
      parameters:
        - name: team_challenge_id
          in: query
          schema:
            type: integer
            example: 1
          required: true
        - name: per_page
          in: query
          schema:
            type: integer
            example: 10
          required: true
        - name: page
          in: query
          schema:
            type: integer
            example: 1
          required: true
      responses:
        '200':
          description: List Team Challenge
          content:
            application/json:
              schema:
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      data:
                        type: object
                        properties:
                          id:
                            type: integer
                            example: 1
                          name:
                            type: string
                            example: Aichi
                          step:
                            type: integer
                            example: 1
                      meta:
                        type: object
                        properties:
                          current_page:
                            type: integer
                            example: 1
                          from:
                            type: integer
                            example: 1
                          last_page:
                            type: integer
                            example: 2
                          path:
                            type: string
                            example: 'https://hitachi.coo.jp/api/v1/team-challenges'
                          per_page:
                            type: integer
                            example: 2
                          to:
                            type: integer
                            example: 2
                          total:
                            type: integer
                            example: 2
                  message:
                    type: string
                    example: success
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
  /team-challenges/{id}:
    get:
      tags:
        - Team Challenge
      summary: Get item team challenges
      description: Get item team challenges
      parameters:
        - name: id
          in: path
          description: id
          schema:
            type: integer
            example: 1
          required: true
      responses:
        '200':
          description: Complete response
          content:
            application/json:
              schema:
                properties:
                  status:
                    type: boolean
                    example: 200
                  message:
                    type: string
                    example: MSG_04
                  data:
                    type: object
                    description: response data
                    example:
                      - id: 1
                        name: 気心の知れた同期
                        total_step_taken: 1
                        total_step_target: "500000"
                        remaining_step: 403835
                        team_step_average: 250000
                        percent_distance_traveled: 19.233
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
  #### Step
  /step:
    get:
      tags:
        - Step
      summary: List Step
      description: List Step
      responses:
        '200':
          description: List Step
          content:
            application/json:
              schema:
                properties:
                  success:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: MSG_04
                  data:
                    type: object
                    properties:
                      total_step_taken:
                        type: integer
                        example: 96165
                      remaining_step:
                        type: integer
                        example: 103835
                      percent_distance_traveled:
                        type: integer
                        example: 48.0825
                      chart:
                        type: array
                        items:
                          properties:
                            month:
                              type: integer
                              example: 08
                            total_step:
                              type: integer
                              example: 7500
                            total_step_months:
                              type: integer
                              example: 7500
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
  #### Setting
  /goal-users:
    get:
      tags:
        - Setting Challenge
      summary: Get item goal user
      description: Get item goal user
      responses:
        '200':
          description: Complete response
          content:
            application/json:
              schema:
                properties:
                  status:
                    type: boolean
                    example: 200
                  message:
                    type: string
                    example: MSG_04
                  data:
                    type: object
                    description: response data
                    example:
                      - id: 1
                        user_id: 1
                        nick_name: "CO-URIBA　Taro"
                        motivational_phrases:  "チームNo1の歩数を目指しています"
                        target_value: 22
                        target_deadline: 2022-11-10
                        taste_ids: [1,2,3]
                        nutrient_ingredient_ids: [4]
                        challenge_theme_id: 1
                        challenge_group_id: 1
        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
  /tastes:
    get:
      tags:
        - Setting Challenge
      summary: Get Tastes
      description: Get Tastes
      responses:
        '200':
          description: Complete response
          content:
            application/json:
              schema:
                properties:
                  status:
                    type: boolean
                    example: 200
                  message:
                    type: string
                    example: MSG_04
                  data:
                    type: object
                    description: response data
                    example:
                      - id: 1
                        name: 甘い
                      - id: 2
                        name: 辛い

        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
  /nutrient-ingredients:
    get:
      tags:
        - Setting Challenge
      summary: Get Nutrient Ingredients
      description: Get Nutrient Ingredients
      responses:
        '200':
          description: Complete response
          content:
            application/json:
              schema:
                properties:
                  status:
                    type: boolean
                    example: 200
                  message:
                    type: string
                    example: MSG_04
                  data:
                    type: object
                    description: response data
                    example:
                      - id: 1
                        name: 脂質
                      - id: 2
                        name: 炭水化物

        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
  /challenge-themes:
    get:
      tags:
        - Setting Challenge
      summary: Get challenge themes
      description: Get challenge themes
      responses:
        '200':
          description: Complete response
          content:
            application/json:
              schema:
                properties:
                  status:
                    type: boolean
                    example: 200
                  message:
                    type: string
                    example: MSG_04
                  data:
                    type: object
                    description: response data
                    example:
                      - id: 1
                        challenge_theme: 日本の名山チャレンジ
                        image_path: "***01.gif"
                      - id: 2
                        challenge_theme: 世界の名山チャレンジ
                        image_path: "***02.gif"

        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
  /challenge-groups:
    get:
      tags:
        - Setting Challenge
      summary: Get challenge groups
      description: Get challenge groups
      responses:
        '200':
          description: Complete response
          content:
            application/json:
              schema:
                properties:
                  status:
                    type: boolean
                    example: 200
                  message:
                    type: string
                    example: MSG_04
                  data:
                    type: object
                    description: response data
                    example:
                      - id: 1
                        name: 気心の知れた同期
                      - id: 2
                        challenge_theme: 苦楽を共にしている会社チームメンバー

        '400':
          $ref: '#/components/responses/400'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
  /setting-challenge:
    post:
      tags:
        - Setting Challenge
      summary: Update setting challenge
      description: Update setting challenge
      requestBody:
        description: Update setting challenge
        content:
          application/json:
            schema:
              type: object
              properties:
                challenge_theme_id:
                  type: integer
                  example: 1
                  required: true
                challenge_group_id:
                  type: integer
                  example: 1
                  required: true
                nick_name:
                  type: string
                  example: CO-URIBA　Taro
                  required: true
                motivational_phrases:
                  type: string
                  example: チームNo1の歩数を目指しています
                  required: true
                target_value:
                  type: string
                  example: 22
                  required: true
                target_deadline:
                  type: string
                  example: 2022-11-10
                  required: true
                taste_ids:
                  type: string
                  example:  [
                    1,
                    2,
                    4
                  ]
                nutrient_ingredient_ids:
                  type: string
                  example: [4]
      responses:
        '200':
          description: Complete response
          content:
            application/json:
              schema:
                properties:
                  success:
                    type: integer
                    example: 200
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      challenge_theme_id:
                        type: integer
                        example: 1
                      challenge_group_id:
                        type: integer
                        example: 1
                      nick_name:
                        type: string
                        example: CO-URIBA　Taro
                      motivational_phrases:
                        type: string
                        example: チームNo1の歩数を目指しています
                      target_value:
                        type: string
                        example: 22
                      target_deadline:
                        type: string
                        example: 2022-11-10
                      taste_ids:
                        type: string
                        example: [
                          1,
                          2,
                          4
                        ]
                      nutrient_ingredient_ids:
                        type: string
                        example: [ 4 ]
                  message:
                    type: string
                    example: MSG_04
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                properties:
                  success:
                    type: boolean
                    example: false
                  errors:
                    type: string
                    example: MSG_045
                  message:
                    type: string
                    example: Bad Request
                  optionFields:
                    type: object
                    description: Field input error
                    example: { }
        '422':
          $ref: '#/components/responses/422'
        '500':
          $ref: '#/components/responses/500'

  /setting-challengex:
    post:
      tags:
        - Setting Challenge
      summary: Update setting challenge
      description: Update setting challenge
      requestBody:
        description: Update setting challenge
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  example: 1
                  required: true
                challenge_group_id:
                  type: integer
                  example: 1
                  required: true
                nick_name:
                  type: string
                  example: CO-URIBA　Taro
                  required: true
                motivational_phrases:
                  type: string
                  example: チームNo1の歩数を目指しています
                  required: true
                target_value:
                  type: string
                  example: 22
                  required: true
                target_deadline:
                  type: string
                  example: 2022-11-10
                  required: true
                taste_ids:
                  type: string
                  example:  [
                    1,
                    2,
                    4
                  ]
                nutrient_ingredient_ids:
                  type: string
                  example: [4]
      responses:
        '200':
          description: Complete response
          content:
            application/json:
              schema:
                properties:
                  success:
                    type: integer
                    example: 200
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      challenge_theme_id:
                        type: integer
                        example: 1
                      challenge_group_id:
                        type: integer
                        example: 1
                      nick_name:
                        type: string
                        example: CO-URIBA　Taro
                      motivational_phrases:
                        type: string
                        example: チームNo1の歩数を目指しています
                      target_value:
                        type: string
                        example: 22
                      target_deadline:
                        type: string
                        example: 2022-11-10
                      taste_ids:
                        type: string
                        example: [
                          1,
                          2,
                          4
                        ]
                      nutrient_ingredient_ids:
                        type: string
                        example: [ 4 ]
                  message:
                    type: string
                    example: MSG_04
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                properties:
                  success:
                    type: boolean
                    example: false
                  errors:
                    type: string
                    example: MSG_045
                  message:
                    type: string
                    example: Bad Request
                  optionFields:
                    type: object
                    description: Field input error
                    example: { }
        '422':
          $ref: '#/components/responses/422'
        '500':
          $ref: '#/components/responses/500'

  #### Confectionery
  /confectioneries:
    get:
      tags:
        - Confectioneries
      summary: List confectioneries
      description: List confectioneries
      parameters:
        - name: per_page
          in: query
          schema:
            type: integer
            example: 10
        - name: page
          in: query
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: List confectioneries
          content:
            application/json:
              schema:
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      data:
                        type: array
                        items:
                          properties:
                            id:
                              type: integer
                              example: 1
                            name:
                              type: string
                              example: ビスケット
                            unit_price:
                              type: integer
                              example: 100
                            image_path:
                              type: string
                              example: https://hac-consulting-bucket.s3.ap-northeast-1.amazonaws.com/products/product1.svg
                      links:
                        type: object
                        properties:
                          first:
                            type: string
                            example: https://hitachi.coo.jp/api/v1/confectioneries?per_page=10&page=1
                          last:
                            type: string
                            example: https://hitachi.coo.jp/api/v1/confectioneries?per_page=10&page=16
                          prev:
                            type: string
                            example: null
                          next:
                            type: string
                            example: https://hitachi.coo.jp/api/v1/confectioneries?per_page=10&page=2
                      meta:
                        type: object
                        properties:
                          current_page:
                            type: integer
                            example: 1
                          from:
                            type: integer
                            example: 1
                          last_page:
                            type: integer
                            example: 2
                          path:
                            type: string
                            example: 'https://hitachi.coo.jp/api/v1/confectioneries'
                          per_page:
                            type: integer
                            example: 2
                          to:
                            type: integer
                            example: 2
                          total:
                            type: integer
                            example: 2
                  message:
                    type: string
                    example: success
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
  #### History
  /history-purchases:
    get:
      tags:
        - History Purchases
      summary: List History Purchases
      description: List History Purchases
      parameters:
        - name: per_page
          in: query
          schema:
            type: integer
            example: 10
        - name: page
          in: query
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: List History Purchases
          content:
            application/json:
              schema:
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      data:
                        type: array
                        items:
                          properties:
                            id:
                              type: integer
                              example: 1
                            date_purchase:
                              type: string
                              example: 2023-10-02 20:46:48
                            quantity:
                              type: integer
                              example: 1
                            unit_price:
                              type: integer
                              example: 110
                            total_price:
                              type: integer
                              example: 110
                            confectioneries:
                              type: array
                              items:
                                properties:
                                  id:
                                    type: integer
                                    example: 1
                                  name:
                                    type: string
                                    example: クラッカー
                      links:
                        type: object
                        properties:
                          first:
                            type: string
                            example: https://hitachi.coo.jp/api/v1/history-purchases?per_page=10&page=1
                          last:
                            type: string
                            example: https://hitachi.coo.jp/api/v1/history-purchases?per_page=10&page=16
                          prev:
                            type: string
                            example: null
                          next:
                            type: string
                            example: https://hitachi.coo.jp/api/v1/history-purchases?per_page=10&page=2
                      meta:
                        type: object
                        properties:
                          current_page:
                            type: integer
                            example: 1
                          from:
                            type: integer
                            example: 1
                          last_page:
                            type: integer
                            example: 2
                          path:
                            type: string
                            example: 'https://hitachi.coo.jp/api/v1/team-challenges'
                          per_page:
                            type: integer
                            example: 2
                          to:
                            type: integer
                            example: 2
                          total:
                            type: integer
                            example: 2
                  message:
                    type: string
                    example: success
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'

components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
  responses:
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            properties:
              errors:
                type: string
                example: BadRequestException
              message:
                type: string
                example: 入力データが違います。
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            properties:
              errors:
                type: string
                example: UnauthorizedException
              message:
                type: string
                example: 権限がありません。
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            properties:
              errors:
                type: string
                example: ForbiddenException
              message:
                type: string
                example: Forbidden resource
    '404':
      description: Not Found
      content:
        application/json:
          schema:
            properties:
              errors:
                type: string
                example: NotFoundException
              message:
                type: string
                example: ページが見つかりません。
    '422':
      description: Unprocessable Entity
      content:
        application/json:
          schema:
            properties:
              errors:
                type: string
                example: NotFoundException
              message:
                type: string
                example: ページが見つかりません。
    '449':
      description: Refresh Token Expired
      content:
        application/json:
          schema:
            properties:
              errors:
                type: string
                example: RefreshTokenExpired
              message:
                type: string
                example: Refresh Token Expired
    '500':
      description: Internal Server
      content:
        application/json:
          schema:
            properties:
              errors:
                type: string
                example: InternalServerError
              message:
                type: string
                example: サーバーに接続エラーがあります。
    '553':
      description: Prescription Expired
      content:
        application/json:
          schema:
            properties:
              errors:
                type: string
                example: PrescriptionExpired
              message:
                type: string
                example: 医師の診察 服薬の有効期限が 過ぎています。 担当医師の診察を 受けてください。
